@baseUrl=https://cicstaging.z1central.com/api/

@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiOGYzOTczMTA0MmU4OWJhODE3NTU2ZmFiY2I3YTdkMDFmNjc5ZmY3NWExNzY1ZDk1MzNjOGU0NTQwYTRjOWI1ZmFlNTY5N2NmZTI5MzY5M2EiLCJpYXQiOjE2NzU2NTYxMzYuMjYwNjI4LCJuYmYiOjE2NzU2NTYxMzYuMjYwNjMxLCJleHAiOjE3MDcxOTIxMzYuMjUxNjE3LCJzdWIiOiI1MiIsInNjb3BlcyI6WyIqIl19.j5zKuMc_luCYM3QEQP8jRKy1Mw5NwKqBFy-eC5mjbMkEypmjkSEMBJK5SAA_WngycvFNHhxlGRzq2g3eu4hEuFPyYZitQm3BCaWqmOkCNvAydkYFUcObDMj6O2I5J27GVydpBYyZajBhlXDPyKX1Q40dVejAzrbi8lJnlDrG9-mF6GiniEHHBu-n7xUMOMFXUgIbN0_Pj_hZ6ZQOsUs-eYKaybwBH_FtogMmWXY01OZQDFdVvyw4RK0nR3RUvrSHwv9rgZJ4yMZQ1uDy5kaBfIu4NlsOClGmo2LddMx3JRXwUu_WuZgfJxiyQJgXE4ZqPRxkV0GtROmhBOkMLBe6uWhSAzTdXibflDbXUBXNWghkkI4ZGx6hrkJyyaOEHJOMj80iOSMeX7wYrqEFpkQDRH-oU74fLhvm0konxbkG3fN4eFC547C_ZdCtvbuD-eYcLPrjZ_2WJ6_Su_bmFOnYkNIsU0VHSAE6jEJw28YagiomOL7RV-p_A9aZBHqzCiRKbt5Ep3QnWj9bNHd8SLNIGdUBMygXyIXEEani4asziB1TFgcay9Q2bYRCJPTEvAWgjeCHLfYEG6F4yhJ2Q-bhyCj9F2M0ntufyVNyKM-NCY3eVe96NT9GZuAyiph_PC_TiGbwvIX3SOVL61m63PqrDMuiWNslM737jW_AnQAhkv4
POST {{baseUrl}}v4/login
Accept: application/json
Content-Type: application/json

{
    "phone" : "+855889002920",
    "password" : "Theara12"   
}

###
POST {{baseUrl}}request-otp
Accept: application/json
Content-Type: application/json

{
    "phone" : "+855889002920"
}

###
POST {{baseUrl}}verify-otp
Accept: application/json
Content-Type: application/json

{
    "phone" : "+855889002920",
    "verify_code": "4893"
}


###
POST {{baseUrl}}user/set-password
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "password" : "Theara123",
    "password_confirmation":"Theara123"
}

###
POST https://pre-cic.z1platform.com/api/v4/register
Content-Type: application/json
Accept: application/json

{
    "phone" : "+855889002920"
}


###
Get {{baseUrl}}v4/user?id=$memberId
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
