@baseUrl=https://cicstaging.z1central.com/api/

@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiMjQ2MjU4NzFlMjM4ZjZhMzRjNmI4Y2U3NWZlZTE0MDU4NDNjZTEyZGJkOGM3NjkxNThkYmI3MDdhYmY4NDI0YzcyYmRhNDBiNGI2MTQxNGQiLCJpYXQiOjE2NzU3NDA2MDcuNjU0NzgsIm5iZiI6MTY3NTc0MDYwNy42NTQ3ODMsImV4cCI6MTcwNzI3NjYwNy42NDI1MDIsInN1YiI6IjUyIiwic2NvcGVzIjpbIioiXX0.XTGrb45Q7MeFBkDT90mRtfD57B05aa6_tSiKcVe2ApwWGkKycX_5E-a04bmowDGInQ3Hx47vZMUD6j_U1tCi3pneC2zge-askeJIipPpKvwoy3iD50n583vUJROaun90USnREL5tsJLhQYM9qLvyXXA_inouSjfztYkaYXozqqvCdG2jiu2Lp21KptkvzDD9JZFFfNTVa5Q2ChWcJ-5JNqqdDKH7skHXG5cWazloHpjcaO9fUWdsHsTlLUYFXjPcJzfNVDyW7RfZ7pn-PfFfY4AoylL9ROJYigNGdoBbyCHaL2r0PL27gPdr0RpgmBdGPhoIB9IFxiMpnAK2jOwm5mfWgJ2b6Ju3fzwZuJmqTCcaON_gg5wFbshtgdAoapm2gnxOvZZY1sD5so80j60gqiT4oU5-7A92gZMkaY22b4k5FqqJ51DsDo_k1Fcl3tS0SiDuSNjyaqRLgnbYUR02swocGDAT6yqK65Hu6Ke98FXRxyM044rHlcpNS63uf0hMoX-HU8naWrraF_oupoAixDBDInnursgPXYvehccr4Ooq8J8o5mgYGm7mNeNtWm_VrrIE0lfwPvwAM5OPlwwi-9k1ZMYqe_WImioUdYcYgCS8nmN1HfUq1jYlSdPrw_UPTjWy8dGnKpNvtXr4IpnlsJjb8fpGdVTs05d62j2M-Mo
POST {{baseUrl}}v4/login
Accept: application/json
Content-Type: application/json

{
    "phone" : "+855889002920",
    "password" : "Theara123"   
}

###
POST {{baseUrl}}request-otp
Accept: application/json
Content-Type: application/json

{
    "phone" : "+855889002920"
}

###
POST {{baseUrl}}verify-otp
Accept: application/json
Content-Type: application/json

{
    "phone" : "+855889002920",
    "verify_code": "4893"
}


###
POST {{baseUrl}}user/set-password
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "password" : "Theara123",
    "password_confirmation":"Theara123"
}

###
POST https://pre-cic.z1platform.com/api/v4/register
Content-Type: application/json
Accept: application/json

{
    "phone" : "+855889002920"
}
    
###
Get {{baseUrl}}v4/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
=======
###
GET {{baseUrl}}v4/slide?module=privilege
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v4/privilege/category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v4/privilege/shop?page=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v4/privilege/shop?favorite
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### favorite or unfavorite  
PUT {{baseUrl}}v4/privilege/shop/3?is_favorite=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


